### PR TITLE
Add ability to abort request on headers callback. Closes typhoeus/typhoeus#511

### PR DESCRIPTION
**Pull request by sharshenov**

### CODE REVIEW

**Comment by i0rek** [comment]
@sharshenov thanks a lot for your work! travis is failing, could you check that?

**Comment by sharshenov** [comment]
Sure. But later

**Comment by sharshenov** [comment]
I have problem with my RVM setup. BTW I applied different approach in my project:

```
def run_request
  request = Typhoeus::Request.new(url, typhoeus_options).tap do |request|
      request.on_headers(&method(:validate_content_type))
      request.on_body(&method(:write))
    end
  request.run
end

def validate_content_type(response)
end
```

**Comment by sharshenov** [comment]
I have problems with 1.8.7 ruby setup.
BTW I don't think that my PR is good enough to be merged. Aborting request should happen before any `body_write_callback` call happen. So I'm cancelling PR.


P.S. If somebody is OK with this PR approach, here is example how to abort request if headers check failed:

```ruby
class RemoteContent
  def initialize(url, content_type)
    @url          = url
    @content_type = content_type
    @content      = ''.b
  end

  def get
    run_request
    @content
  end

  private

  def run_request
    request = Typhoeus::Request.new(@url).tap do |typhoeus|
      typhoeus.on_headers(&method(:validate_content_type))
      typhoeus.on_body(&method(:write))
    end

    request.run
  end

  def write(chunk, _)
    return :abort unless @content_type_valid
    @content << chunk
  end

  def validate_content_type(response)
    @content_type_valid = response.headers['Content-Type'].include?('text/html')
  end
end
```

**Pull request closed without merging**
