### PR TITLE
Easy::Operations#handle: Thread-safe cleanup

### PR DESCRIPTION
**Pull request by Zapotek**
This change fixes intermittent segfaults.
Unfortunately I don't have an easily reproducible test-case but this change seems to 
fix segfaults for a live system.

### CODE REVIEW

**Comment by Zapotek** [comment]
Check that, segfaults started re-appearing.

**Comment by i0rek** [comment]
:( does that mean this fix doesn't help?

**Comment by Zapotek** [comment]
Unfortunately yes and I'm not sure what else it might be.
I'll see if I can narrow it down but I'm not very experienced with FFI so I'm not hopeful.

**Comment by niko-pax-uofa** [comment]
This issue you are trying to address is related to ( probably the cause of) https://github.com/typhoeus/typhoeus/issues/452

**Comment by Zapotek** [comment]
This is a very old PR but when using Ruby 2.7.1 segfaults became a clear show stopper in my use-case as `easy_cleanup` started to always segfault after a while.

This fix immediately took care of my issue although I'm not sure if it'll be 100% effective for all multi-thread related segfaults.

I think it's worth merging into `master`.

**Comment by arianf** [comment]
I don't think this has fixed the sigfaults for us. We are still seeing them, I've filed: https://github.com/typhoeus/ethon/issues/209

**Pull request merged**
