### PR TITLE
feat: adding all http2 options

### PR DESCRIPTION
**Pull request by Andrapyre**
This PR adds all http2 options as well as some brief documentation explaining how to use them.

### CODE REVIEW

**Comment by Andrapyre** [comment]
@Kjarrigan , could we have some help to speed this CR up?

**Comment by Kjarrigan** [comment]
Sorry for the late reply. I'm now back from vacation. LGTM and thanks for the contribution

**Comment by Kjarrigan** [comment]
@i0rek can we get a new (point) release?

**Comment by i0rek** [comment]
@Andrapyre @Kjarrigan ethon 0.16.0 is released. Thank you for your work! 🙇

**Pull request merged**
